name: "💡 Feature Request"
description: Create a new ticket for a new feature request
title: "💡 [REQUEST] - <title>"
labels: [
  "enhancement"
]
body:
  - type: input
    id: concise_title
    attributes:
      label: "Concise Description"
      placeholder: write a concise and appropraiate one line description of the feature request / idea
    validations:
      required: true
  - type: textarea
    id: About_Feature
    attributes:
      label: "About Feature"
      description: About Feature Request
      placeholder: "Write about the idea in detail, about how it will be useful and which problem would it solve"
    validations:
      required: true
  - type: textarea
    id: Solution
    attributes:
      label: "Solution Proposed"
      description: Write your solution that could solve this feature request
      placeholder: "Write about the hypothetical solution you propose"
    validations:
      required: false
  - type: textarea
    id: reference_issues
    attributes:
      label: "Reference Issues"
      description: Common issues that you think is relevant to this feature request
      placeholder: "#Issues IDs"
    validations:
      required: false
  - type: textarea
    id: basic_example
    attributes:
      label: "Additional Info"
      description: Write the facts or additional information that you think should be considered for the solution.
      placeholder: A few specific words would be enough.
    validations:
      required: false
  - type: textarea
    id: drawbacks
    attributes:
      label: "Drawbacks"
      description: What are the drawbacks/impacts of your feature request ?
      placeholder: Identify the drawbacks and impacts while being neutral on your feature request
    validations:
      required: false
  - type: textarea
    id: unresolved_question
    attributes:
      label: "Unresolved questions"
      description: What questions still remain unresolved ?
      placeholder: Identify any unresolved issues.
    validations:
      required: false
  - type: checkboxes
    id: coc
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct]()
      options:
        - label: I follow [Contributing Guidelines](https://github.com/Anmol-Baranwal/Awesome-Illustrations-4Projects/blob/main/CONTRIBUTING.md) of this project.
          required: true
