name: Auto message on First Issue

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.ISSUES_PR }}
          issue-message: '  Hello there!👋 Welcome to the project!🚀 Thank you and congrats🎉 for opening your very first issue in this project. '
